import { settingsToToml, findClaudeReferences, redactEnvValue } from '../utils.js';

/**
 * Convert Claude Code settings.json to Codex config.toml
 * MCP servers are handled separately by mcp-converter
 */
export function convertSettings(inventory) {
  const warnings = [];
  const settings = inventory.settings || {};
  const settingsLocal = inventory.settingsLocal || {};
  const merged = { ...settings, ...settingsLocal };

  let toml = '# Generated by cc2codex\n# https://github.com/openai/codex\n\n';

  // Model configuration
  toml += '# Model Configuration\n';
  if (merged.model) {
    toml += `# Original Claude model: ${merged.model}\n`;
    warnings.push(`Model "${merged.model}" mapped to Codex default — update manually if needed`);
  }
  toml += 'model = "gpt-5.4"\n';

  if (merged.reasoning_effort || merged.modelReasoningEffort) {
    const effort = merged.reasoning_effort || merged.modelReasoningEffort;
    toml += `model_reasoning_effort = "${effort}"\n`;
  } else {
    toml += 'model_reasoning_effort = "high"\n';
  }
  toml += '\n';

  // Sandbox mode
  toml += '# Sandbox Mode\n';
  toml += '# Options: "workspace-write" (default), "read-only", "danger-full-access"\n';
  if (merged.permissions) {
    const hasWildcardAllow = merged.permissions.allow?.includes('*');
    if (hasWildcardAllow) {
      toml += 'sandbox_mode = "danger-full-access"\n';
      warnings.push('Wildcard allow permission detected — mapped to danger-full-access');
    } else {
      toml += 'sandbox_mode = "workspace-write"\n';
    }
  } else {
    toml += 'sandbox_mode = "workspace-write"\n';
  }
  toml += '\n';

  // Approval policy
  toml += '# Approval Policy\n';
  toml += '# Options: "on-request" (default), "untrusted", "never"\n';
  if (merged.autoApprove || merged.dangerouslySkipPermissions) {
    toml += 'approval_policy = "never"\n';
    warnings.push('Auto-approve was enabled — mapped to approval_policy = "never"');
  } else {
    toml += 'approval_policy = "on-request"\n';
  }
  toml += '\n';

  // History persistence
  toml += '# Conversation History\n';
  toml += '[history]\n';
  if (merged.historyPersistence === false || merged.saveHistory === false) {
    toml += 'persistence = "none"\n';
  } else {
    toml += 'persistence = "save-all"\n';
  }
  toml += 'max_bytes = 1048576\n';
  toml += '\n';

  // Environment variables as comments
  if (inventory.envVars && Object.keys(inventory.envVars).length > 0) {
    toml += '# Environment Variables\n';
    toml += '# Codex reads env vars from the shell. Recreate these in your shell profile:\n';
    for (const [key] of Object.entries(inventory.envVars)) {
      toml += `# export ${key}="${redactEnvValue(key)}"\n`;
    }
    toml += '\n';
    warnings.push(
      `${Object.keys(inventory.envVars).length} env var name(s) noted as comments — values were redacted for safety`
    );
  }

  // Permissions as comments (informational — Codex uses sandbox_mode instead)
  if (inventory.permissions.allow.length > 0 || inventory.permissions.deny.length > 0) {
    toml += '# Claude Code Permissions (for reference — Codex uses sandbox_mode instead)\n';
    for (const rule of inventory.permissions.allow) {
      toml += `# allow: ${rule}\n`;
    }
    for (const rule of inventory.permissions.deny) {
      toml += `# deny: ${rule}\n`;
    }
    toml += '\n';
    warnings.push(
      'Permission rules written as comments — Codex uses sandbox_mode instead of allow/deny lists'
    );
  }

  // Check for Claude-specific references in any raw setting values
  const settingsStr = JSON.stringify(merged);
  const refs = findClaudeReferences(settingsStr);
  if (refs.length > 0) {
    warnings.push(`Claude-specific references in settings: ${refs.join(', ')}`);
  }

  return { toml, warnings };
}
