import { homedir } from 'os';
import { join, dirname } from 'path';
import { readFileSync, existsSync, statSync } from 'fs';

export function resolveClaudeHome() {
  return join(homedir(), '.claude');
}

export function resolveCodexHome() {
  return join(homedir(), '.codex');
}

export function resolveAgentsHome(codexHome = null) {
  if (codexHome) {
    const defaultCodexHome = resolveCodexHome();
    if (codexHome !== defaultCodexHome) {
      return join(dirname(codexHome), '.agents');
    }
  }

  return join(homedir(), '.agents');
}

export function readJsonSafe(filePath) {
  try {
    if (!existsSync(filePath)) return null;
    return JSON.parse(readFileSync(filePath, 'utf-8'));
  } catch {
    return null;
  }
}

export function readFileSafe(filePath) {
  try {
    if (!existsSync(filePath)) return null;
    return readFileSync(filePath, 'utf-8');
  } catch {
    return null;
  }
}

export function fileSizeBytes(filePath) {
  try {
    return statSync(filePath).size;
  } catch {
    return 0;
  }
}

export function isSensitiveEnvKey(key = '') {
  return /key|token|secret|password|api/i.test(key);
}

export function redactEnvValue(key, value = '<set in shell>') {
  if (isSensitiveEnvKey(key)) {
    return '<set in shell>';
  }

  return value;
}

/**
 * Convert a JSON MCP server config to TOML string
 */
export function mcpServerToToml(name, config) {
  let toml = `[mcp_servers.${name}]\n`;
  if (config.command) toml += `command = "${config.command}"\n`;
  if (config.args) toml += `args = [${config.args.map(a => `"${a}"`).join(', ')}]\n`;
  if (config.env) {
    const envParts = Object.entries(config.env)
      .map(([k, v]) => `${k} = "${redactEnvValue(k, v)}"`)
      .join(', ');
    toml += `env = { ${envParts} }\n`;
  }
  toml += `enabled = true\n`;
  return toml;
}

export function normalizeMcpConfig(config = {}) {
  const sourceDir = config.source ? dirname(config.source) : null;
  const replacePluginRoot = (value) => {
    if (typeof value !== 'string') return value;
    if (!sourceDir) return value;
    return value.replaceAll('${CLAUDE_PLUGIN_ROOT}', sourceDir);
  };

  const normalized = {
    ...config,
    command: replacePluginRoot(config.command),
    args: Array.isArray(config.args) ? config.args.map(replacePluginRoot) : config.args,
  };

  if (config.env && typeof config.env === 'object') {
    normalized.env = Object.fromEntries(
      Object.entries(config.env).map(([key, value]) => [key, replacePluginRoot(value)])
    );
  }

  return normalized;
}

/**
 * Parse markdown frontmatter from a skill/agent file
 */
export function parseFrontmatter(content) {
  const match = content.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) return { frontmatter: {}, body: content };

  const lines = match[1].split('\n');
  const frontmatter = {};
  for (const line of lines) {
    const idx = line.indexOf(':');
    if (idx > 0) {
      const key = line.slice(0, idx).trim();
      const val = line.slice(idx + 1).trim();
      frontmatter[key] = val;
    }
  }
  return { frontmatter, body: match[2] };
}

/**
 * Detect Claude-specific references in content
 */
export function findClaudeReferences(content) {
  const refs = [];
  const patterns = [
    { pattern: /\bAgent\b.*tool/gi, label: 'Agent tool (no Codex equivalent — use codex exec or multi-terminal)' },
    { pattern: /\bTeamCreate\b/gi, label: 'TeamCreate (no Codex equivalent)' },
    { pattern: /\bEnterPlanMode\b/gi, label: 'EnterPlanMode (use /plan in Codex)' },
    { pattern: /\bExitPlanMode\b/gi, label: 'ExitPlanMode (use Shift+Tab in Codex)' },
    { pattern: /\bSendMessage\b/gi, label: 'SendMessage (no Codex equivalent)' },
    { pattern: /\bTaskCreate\b/gi, label: 'TaskCreate (no direct Codex equivalent)' },
    { pattern: /\bTaskUpdate\b/gi, label: 'TaskUpdate (no direct Codex equivalent)' },
    { pattern: /\bNotebookEdit\b/gi, label: 'NotebookEdit (check Codex notebook support)' },
    { pattern: /\bSkill\b.*tool/gi, label: 'Skill tool (use $ or /skills in Codex)' },
    { pattern: /claude\.ai/gi, label: 'claude.ai URL reference' },
    { pattern: /anthropic/gi, label: 'Anthropic reference' },
    { pattern: /Claude Code/gi, label: 'Claude Code reference' },
    { pattern: /settings\.json/gi, label: 'settings.json (use config.toml in Codex)' },
    { pattern: /settings\.local\.json/gi, label: 'settings.local.json (use config.toml in Codex)' },
    { pattern: /CLAUDE\.md/gi, label: 'CLAUDE.md (use AGENTS.md in Codex)' },
    { pattern: /~\/\.claude\//gi, label: '~/.claude/ path (use ~/.codex/ in Codex)' },
  ];

  for (const { pattern, label } of patterns) {
    if (pattern.test(content)) {
      refs.push(label);
    }
    pattern.lastIndex = 0; // reset regex
  }

  return refs;
}

/**
 * Generate TOML string from a settings object
 */
export function settingsToToml(settings) {
  let toml = '# Generated by cc2codex\n# https://github.com/openai/codex\n\n';

  // Model settings
  toml += '# Model Configuration\n';
  toml += 'model = "gpt-5.4"\n';
  toml += 'model_reasoning_effort = "high"\n\n';

  // Sandbox
  toml += '# Sandbox Mode\n';
  toml += '# Options: "workspace-write" (default), "read-only", "danger-full-access"\n';
  toml += 'sandbox_mode = "workspace-write"\n\n';

  // Approval policy
  toml += '# Approval Policy\n';
  toml += '# Options: "on-request" (default), "untrusted", "never"\n';
  toml += 'approval_policy = "on-request"\n\n';

  // History
  toml += '# Conversation History\n';
  toml += '[history]\n';
  toml += 'persistence = "save-all"\n';
  toml += 'max_bytes = 1048576\n\n';

  return toml;
}
